In [2]:
import pandas as pd
from tabulate import tabulate
import pyodbc
import os, sys
#connection_string ="Driver={ODBC Driver 17 for SQL Server};Server=SSBDN93JS3\\SQLEXPRESS;Database=MyStoreDW;Trusted_Connection=yes;"
connection_string ="Driver={ODBC Driver 17 for SQL Server};Server=MY_GENIE\SQLEXPRESS;Database=ACCIDENTS;Trusted_Connection=yes;"
cnxn = pyodbc.connect(connection_string)
#
cursor = cnxn.cursor()
#
def queryResult(tItle,qUery, oUtFile):
    cursor.execute(my_query)
    col_names = [i[0] for i in cursor.description]
    result = pd.DataFrame.from_records(cursor, columns=col_names)
    with open(oUtFile, 'a') as f:
        print("\n\n", tItle, file=f)
        print("\n\n", qUery, file=f)
        print("\n\n", tabulate(result, headers = col_names, tablefmt="grid", showindex="always"), file=f)
#

## Creating Views

## View 1

In [3]:
import pyodbc
from tabulate import tabulate


# Title for the output
title = "We are creating a view temp1 which contains columns from accident table along with car maker, age of vehicle and driver gender."

# SQL query to execute
my_query = """
create or alter view temp1 as 
select a.*, v.make, v.Age_of_Vehicle, v.Sex_of_Driver
from [dbo].[Vehicle] v
join [dbo].[Accidents] a
on v.Accident_Index = a.Accident_Index;
"""

# Print the title and the SQL query
print(title)
print("\nSQL Query:")
print(my_query)

# Execute the query

We are creating a view temp1 which contains columns from accident table along with car maker, age of vehicle and driver gender.

SQL Query:

create or alter view temp1 as
select a.*, v.make, v.Age_of_Vehicle, v.Sex_of_Driver
from [dbo].[Vehicle] v
join [dbo].[Accidents] a
on v.Accident_Index = a.Accident_Index;

## View 2

In [4]:
import pyodbc
from tabulate import tabulate


# Title for the output
title = "Our view temp2 contains all the accident table columns along with interpretation of whether police arrived at the incident or not."

# SQL query to execute
my_query = """
create or alter view  temp2 as 
select a.*,p.Meaning
from [dbo].[Accidents] a
join [dbo].[Police_Attendance] p
on a.Did_Police_Officer_Attend_Scene_Of_Accident = p.Did_Police_Officer_Attend_Scene_Of_Accident
create or alter view  temp2 as 
select a.*,p.Meaning
from [dbo].[Accidents] a
join [dbo].[Police_Attendance] p
on a.Did_Police_Officer_Attend_Scene_Of_Accident = p.Did_Police_Officer_Attend_Scene_Of_Accident

"""

# Print the title and the SQL query
print(title)
print("\nSQL Query:")
print(my_query)

# Execute the query

Our view temp2 contains all the accident table columns along with interpretation of whether police arrived at the incident or not.

SQL Query:

create or alter view  temp2 as
select a.*,p.Meaning
from [dbo].[Accidents] a
join [dbo].[Police_Attendance] p
on a.Did_Police_Officer_Attend_Scene_Of_Accident = p.Did_Police_Officer_Attend_Scene_Of_Accident
create or alter view  temp2 as
select a.*,p.Meaning
from [dbo].[Accidents] a
join [dbo].[Police_Attendance] p
on a.Did_Police_Officer_Attend_Scene_Of_Accident = p.Did_Police_Officer_Attend_Scene_Of_Accident

## Query on view 1 & aggregation 1

In [5]:
import pyodbc
from tabulate import tabulate

# Connection string to connect to the SQL Server database

cnxn = pyodbc.connect(connection_string)
cursor = cnxn.cursor()

# Title for the output
title = "This query calculates the total number of unique accidents for each vehicle make, sorting the results in descending order by the number of accidents."

# SQL query to execute
my_query = """
select  make,count(distinct Accident_Index) as No_of_accidents
from temp1
group by make
order by No_of_accidents desc;
"""

# Print the title and the SQL query
print(title)
print("\nSQL Query:")
print(my_query)

# Execute the query
cursor.execute(my_query)

# Fetch all the results
rows = cursor.fetchall()

# Define the headers, if your result includes headers you can fetch them via cursor.description
headers = [column[0] for column in cursor.description]

# Printing the results in a table format
print("\nResults:")
print(tabulate(rows, headers=headers, tablefmt='grid'))

# Clean up: close the cursor and the connection
cursor.close()
cnxn.close()

This query calculates the total number of unique accidents for each vehicle make, sorting the results in descending order by the number of accidents.

SQL Query:

select  make,count(distinct Accident_Index) as No_of_accidents
from temp1
group by make
order by No_of_accidents desc;


Results:
+----------------------------+-------------------+
| make                       |   No_of_accidents |
+============================+===================+
| VAUXHALL                   |             31971 |
+----------------------------+-------------------+
| FORD                       |             31387 |
+----------------------------+-------------------+
| PEUGEOT                    |             17333 |
+----------------------------+-------------------+
| VOLKSWAGEN                 |             16835 |
+----------------------------+-------------------+
| RENAULT                    |             15232 |
+----------------------------+-------------------+
| HONDA                      |             13878 |
+----------------------------+-------------------+
|                            |             13467 |
+----------------------------+-------------------+
| MERCEDES                   |             12434 |
+----------------------------+-------------------+
| TOYOTA                     |             11560 |
+----------------------------+-------------------+
| CITROEN                    |             11070 |
+----------------------------+-------------------+
| NISSAN                     |              9541 |
+----------------------------+-------------------+
| BMW                        |              9384 |
+----------------------------+-------------------+
| FIAT                       |              8024 |
+----------------------------+-------------------+
| VOLVO                      |              7917 |
+----------------------------+-------------------+
| AUDI                       |              7117 |
+----------------------------+-------------------+
| SUZUKI                     |              5734 |
+----------------------------+-------------------+
| ROVER                      |              4307 |
+----------------------------+-------------------+
| SKODA                      |              4047 |
+----------------------------+-------------------+
| YAMAHA                     |              3847 |
+----------------------------+-------------------+
| LAND ROVER                 |              3528 |
+----------------------------+-------------------+
| HYUNDAI                    |              3123 |
+----------------------------+-------------------+
| MAZDA                      |              3061 |
+----------------------------+-------------------+
| SEAT                       |              2998 |
+----------------------------+-------------------+
| MITSUBISHI                 |              2927 |
+----------------------------+-------------------+
| KIA                        |              2715 |
+----------------------------+-------------------+
| SCANIA                     |              2447 |
+----------------------------+-------------------+
| MINI                       |              2372 |
+----------------------------+-------------------+
| DENNIS                     |              2241 |
+----------------------------+-------------------+
| KAWASAKI                   |              2039 |
+----------------------------+-------------------+
| DAF TRUCKS                 |              1817 |
+----------------------------+-------------------+
| PIAGGIO                    |              1524 |
+----------------------------+-------------------+
| LONDON TAXIS INT           |              1351 |
+----------------------------+-------------------+
| MAN                        |              1306 |
+----------------------------+-------------------+
| ALEXANDER DENNIS           |              1301 |
+----------------------------+-------------------+
| JAGUAR                     |              1298 |
+----------------------------+-------------------+
| IVECO                      |              1288 |
+----------------------------+-------------------+
| SAAB                       |              1185 |
+----------------------------+-------------------+
| MG                         |               943 |
+----------------------------+-------------------+
| TRIUMPH                    |               936 |
+----------------------------+-------------------+
| APRILIA                    |               919 |
+----------------------------+-------------------+
| LEXUS                      |               745 |
+----------------------------+-------------------+
| ALFA ROMEO                 |               701 |
+----------------------------+-------------------+
| DAEWOO                     |               701 |
+----------------------------+-------------------+
| CHEVROLET                  |               685 |
+----------------------------+-------------------+
| IVECO-FORD                 |               652 |
+----------------------------+-------------------+
| SUBARU                     |               652 |
+----------------------------+-------------------+
| CHRYSLER                   |               563 |
+----------------------------+-------------------+
| SMART                      |               532 |
+----------------------------+-------------------+
| DAF                        |               462 |
+----------------------------+-------------------+
| DAIHATSU                   |               452 |
+----------------------------+-------------------+
| JEEP                       |               428 |
+----------------------------+-------------------+
| HARLEY-DAVIDSON            |               403 |
+----------------------------+-------------------+
| OPTARE                     |               353 |
+----------------------------+-------------------+
| LDV                        |               340 |
+----------------------------+-------------------+
| PROTON                     |               328 |
+----------------------------+-------------------+
| PORSCHE                    |               326 |
+----------------------------+-------------------+
| LEXMOTO                    |               295 |
+----------------------------+-------------------+
| SYM                        |               270 |
+----------------------------+-------------------+
| DUCATI                     |               268 |
+----------------------------+-------------------+
| ERF                        |               257 |
+----------------------------+-------------------+
| ISUZU                      |               253 |
+----------------------------+-------------------+
| GILERA                     |               244 |
+----------------------------+-------------------+
| RENAULT TRUCKS             |               238 |
+----------------------------+-------------------+
| KTM                        |               219 |
+----------------------------+-------------------+
| JOHN DEERE                 |               206 |
+----------------------------+-------------------+
| FODEN                      |               189 |
+----------------------------+-------------------+
| KYMCO                      |               188 |
+----------------------------+-------------------+
| ISUZU TRUCKS               |               157 |
+----------------------------+-------------------+
| LEYLAND                    |               153 |
+----------------------------+-------------------+
| TRANSBUS INT               |               153 |
+----------------------------+-------------------+
| WRIGHTBUS                  |               129 |
+----------------------------+-------------------+
| MCC                        |               126 |
+----------------------------+-------------------+
| NEW HOLLAND                |               119 |
+----------------------------+-------------------+
| JCB                        |               119 |
+----------------------------+-------------------+
| MASSEY FERGUSON            |               106 |
+----------------------------+-------------------+
| LONDON TAXIS INT.          |               102 |
+----------------------------+-------------------+
| QINGQI                     |                98 |
+----------------------------+-------------------+
| DODGE (USA)                |                93 |
+----------------------------+-------------------+
| TAIWAN GOLDEN BEE          |                90 |
+----------------------------+-------------------+
| DACIA                      |                87 |
+----------------------------+-------------------+
| AJS                        |                87 |
+----------------------------+-------------------+
| PULSE                      |                87 |
+----------------------------+-------------------+
| BAOTIAN                    |                85 |
+----------------------------+-------------------+
| DERBI                      |                85 |
+----------------------------+-------------------+
| AUSTIN                     |                82 |
+----------------------------+-------------------+
| OTHER BRITISH              |                77 |
+----------------------------+-------------------+
| OPEL                       |                75 |
+----------------------------+-------------------+
| PERODUA                    |                74 |
+----------------------------+-------------------+
| LEYLAND DAF                |                73 |
+----------------------------+-------------------+
| HYOSUNG                    |                67 |
+----------------------------+-------------------+
| SSANGYONG                  |                66 |
+----------------------------+-------------------+
| CASE IH                    |                62 |
+----------------------------+-------------------+
| KEEWAY                     |                61 |
+----------------------------+-------------------+
| MOTO GUZZI                 |                61 |
+----------------------------+-------------------+
| VESPA (DOUGLAS)            |                61 |
+----------------------------+-------------------+
| SEDDON/ATKINSON            |                59 |
+----------------------------+-------------------+
| VDL                        |                55 |
+----------------------------+-------------------+
| CAGIVA                     |                55 |
+----------------------------+-------------------+
| BENTLEY                    |                55 |
+----------------------------+-------------------+
| BUELL                      |                53 |
+----------------------------+-------------------+
| MITSUBISHI FUSO            |                49 |
+----------------------------+-------------------+
| LOTUS                      |                48 |
+----------------------------+-------------------+
| LAMBRETTA                  |                48 |
+----------------------------+-------------------+
| CPI                        |                44 |
+----------------------------+-------------------+
| LIFAN                      |                42 |
+----------------------------+-------------------+
| METROCAB                   |                41 |
+----------------------------+-------------------+
| PIONEER                    |                41 |
+----------------------------+-------------------+
| GENERIC                    |                41 |
+----------------------------+-------------------+
| ASTON MARTIN               |                41 |
+----------------------------+-------------------+
| CARBODIES                  |                40 |
+----------------------------+-------------------+
| LONGJIA                    |                40 |
+----------------------------+-------------------+
| JONWAY                     |                39 |
+----------------------------+-------------------+
| IRIS.BUS                   |                38 |
+----------------------------+-------------------+
| SUKIDA                     |                38 |
+----------------------------+-------------------+
| HINO                       |                37 |
+----------------------------+-------------------+
| JINLUN                     |                36 |
+----------------------------+-------------------+
| LML                        |                34 |
+----------------------------+-------------------+
| SHINERAY                   |                32 |
+----------------------------+-------------------+
| ROYAL ENFIELD              |                32 |
+----------------------------+-------------------+
| RIEJU                      |                31 |
+----------------------------+-------------------+
| RELIANT                    |                31 |
+----------------------------+-------------------+
| MBK                        |                30 |
+----------------------------+-------------------+
| BEDFORD                    |                29 |
+----------------------------+-------------------+
| ABARTH                     |                27 |
+----------------------------+-------------------+
| CLAAS                      |                27 |
+----------------------------+-------------------+
| SKYJET                     |                27 |
+----------------------------+-------------------+
| TVR                        |                26 |
+----------------------------+-------------------+
| MCW                        |                26 |
+----------------------------+-------------------+
| BSA                        |                25 |
+----------------------------+-------------------+
| FENDT                      |                25 |
+----------------------------+-------------------+
| FERRARI                    |                24 |
+----------------------------+-------------------+
| MOTO ROMA                  |                24 |
+----------------------------+-------------------+
| DAELIM                     |                23 |
+----------------------------+-------------------+
| SUPERBYKE                  |                23 |
+----------------------------+-------------------+
| WHITE KNUCKLE              |                23 |
+----------------------------+-------------------+
| MORRIS                     |                22 |
+----------------------------+-------------------+
| WK BIKES                   |                21 |
+----------------------------+-------------------+
| MASERATI                   |                20 |
+----------------------------+-------------------+
| OTHER ITALIAN              |                20 |
+----------------------------+-------------------+
| HUONIAO                    |                20 |
+----------------------------+-------------------+
| BMC                        |                20 |
+----------------------------+-------------------+
| BOVA                       |                19 |
+----------------------------+-------------------+
| CHEVROLET GMC              |                19 |
+----------------------------+-------------------+
| DODGE                      |                19 |
+----------------------------+-------------------+
| KINROAD                    |                19 |
+----------------------------+-------------------+
| SKYTEAM                    |                19 |
+----------------------------+-------------------+
| ITALJET                    |                18 |
+----------------------------+-------------------+
| MCCORMICK                  |                18 |
+----------------------------+-------------------+
| MOTOR HISPANIA             |                17 |
+----------------------------+-------------------+
| VALTRA                     |                17 |
+----------------------------+-------------------+
| Z Y MOTOR                  |                16 |
+----------------------------+-------------------+
| NORTON                     |                16 |
+----------------------------+-------------------+
| FORD NEW HOLLAND           |                16 |
+----------------------------+-------------------+
| HAOTIAN                    |                15 |
+----------------------------+-------------------+
| MICROCAR                   |                15 |
+----------------------------+-------------------+
| MALAGUTI                   |                15 |
+----------------------------+-------------------+
| ZNEN                       |                15 |
+----------------------------+-------------------+
| SINNIS                     |                15 |
+----------------------------+-------------------+
| SMC                        |                15 |
+----------------------------+-------------------+
| SMITHS                     |                15 |
+----------------------------+-------------------+
| TALBOT                     |                14 |
+----------------------------+-------------------+
| SACHS                      |                14 |
+----------------------------+-------------------+
| WANGYE                     |                14 |
+----------------------------+-------------------+
| MZ                         |                14 |
+----------------------------+-------------------+
| HUSQVARNA                  |                14 |
+----------------------------+-------------------+
| DAIMLER                    |                14 |
+----------------------------+-------------------+
| CCM                        |                14 |
+----------------------------+-------------------+
| AIXAM                      |                14 |
+----------------------------+-------------------+
| ADLY                       |                13 |
+----------------------------+-------------------+
| BENELLI                    |                13 |
+----------------------------+-------------------+
| CAETANO                    |                13 |
+----------------------------+-------------------+
| HUATIAN                    |                13 |
+----------------------------+-------------------+
| DS                         |                13 |
+----------------------------+-------------------+
| ZONGSHEN                   |                13 |
+----------------------------+-------------------+
| TAMORETTI                  |                13 |
+----------------------------+-------------------+
| SONIK                      |                13 |
+----------------------------+-------------------+
| TAISHAN                    |                12 |
+----------------------------+-------------------+
| ZONTES                     |                12 |
+----------------------------+-------------------+
| YIYING                     |                12 |
+----------------------------+-------------------+
| VALMET                     |                12 |
+----------------------------+-------------------+
| VICTORY                    |                11 |
+----------------------------+-------------------+
| TATA                       |                11 |
+----------------------------+-------------------+
| CATERHAM                   |                11 |
+----------------------------+-------------------+
| MANITOU                    |                11 |
+----------------------------+-------------------+
| KUBOTA                     |                11 |
+----------------------------+-------------------+
| LIEBHERR                   |                10 |
+----------------------------+-------------------+
| KAISAR                     |                10 |
+----------------------------+-------------------+
| EASY RIDER                 |                10 |
+----------------------------+-------------------+
| VAN HOOL                   |                10 |
+----------------------------+-------------------+
| ZETOR                      |                 9 |
+----------------------------+-------------------+
| BTM                        |                 9 |
+----------------------------+-------------------+
| AUSTIN MORRIS              |                 9 |

## Join 1 aggregation 2

In [6]:
import pyodbc
from tabulate import tabulate

# Connection string to connect to the SQL Server database
#connection_string = "Driver={ODBC Driver 17 for SQL Server};Server=MY_GENIE\\SQLEXPRESS;Database=OLAP;Trusted_Connection=yes;"
cnxn = pyodbc.connect(connection_string)
cursor = cnxn.cursor()

# Title for the output
title = "This query calculates the total number of accidents for each year and local highway authority, sorting the results by year"

# SQL query to execute
my_query = """
select  year,Local_Highway_Authority,count(*) as No_of_accidents
from [dbo].[Accidents] a
join [dbo].[Dates] d
on a.Date=d.Date
group by year,Local_Highway_Authority
order by year 
"""

# Print the title and the SQL query
print(title)
print("\nSQL Query:")
print(my_query)

# Execute the query
cursor.execute(my_query)

# Fetch all the results
rows = cursor.fetchall()

# Define the headers, if your result includes headers you can fetch them via cursor.description
headers = [column[0] for column in cursor.description]

# Printing the results in a table format
print("\nResults:")
print(tabulate(rows, headers=headers, tablefmt='grid'))

# Clean up: close the cursor and the connection
cursor.close()
cnxn.close()

This query calculates the total number of accidents for each year and local highway authority, sorting the results by year

SQL Query:

select  year,Local_Highway_Authority,count(*) as No_of_accidents
from [dbo].[Accidents] a
join [dbo].[Dates] d
on a.Date=d.Date
group by year,Local_Highway_Authority
order by year


Results:
+--------+--------------------------------------+-------------------+
|   year | Local_Highway_Authority              |   No_of_accidents |
+========+======================================+===================+
|   2005 | Wolverhampton                        |                60 |
+--------+--------------------------------------+-------------------+
|   2005 | Shropshire                           |                52 |
+--------+--------------------------------------+-------------------+
|   2005 | Hammersmith and Fulham               |                39 |
+--------+--------------------------------------+-------------------+
|   2005 | Torbay                               |                33 |
+--------+--------------------------------------+-------------------+
|   2005 | Trafford                             |                52 |
+--------+--------------------------------------+-------------------+
|   2005 | Surrey                               |               344 |
+--------+--------------------------------------+-------------------+
|   2005 | Rotherham                            |                54 |
+--------+--------------------------------------+-------------------+
|   2005 | Milton Keynes                        |                69 |
+--------+--------------------------------------+-------------------+
|   2005 | Torfaen                              |                12 |
+--------+--------------------------------------+-------------------+
|   2005 | Oldham                               |                49 |
+--------+--------------------------------------+-------------------+
|   2005 | Pembrokeshire                        |                26 |
+--------+--------------------------------------+-------------------+
|   2005 | Barnet                               |                83 |
+--------+--------------------------------------+-------------------+
|   2005 | Doncaster                            |                86 |
+--------+--------------------------------------+-------------------+
|   2005 | Oxfordshire                          |               143 |
+--------+--------------------------------------+-------------------+
|   2005 | North Lanarkshire                    |                72 |
+--------+--------------------------------------+-------------------+
|   2005 | Sandwell                             |                61 |
+--------+--------------------------------------+-------------------+
|   2005 | Na h-Eileanan an Iar (Western Isles) |                 5 |
+--------+--------------------------------------+-------------------+
|   2005 | Hounslow                             |                57 |
+--------+--------------------------------------+-------------------+
|   2005 | Warwickshire                         |               140 |
+--------+--------------------------------------+-------------------+
|   2005 | Renfrewshire                         |                33 |
+--------+--------------------------------------+-------------------+
|   2005 | Richmond upon Thames                 |                39 |
+--------+--------------------------------------+-------------------+
|   2005 | Wiltshire                            |               113 |
+--------+--------------------------------------+-------------------+
|   2005 | West Sussex                          |               174 |
+--------+--------------------------------------+-------------------+
|   2005 | East Lothian                         |                12 |
+--------+--------------------------------------+-------------------+
|   2005 | Enfield                              |                61 |
+--------+--------------------------------------+-------------------+
|   2005 | Southampton                          |                56 |
+--------+--------------------------------------+-------------------+
|   2005 | Brent                                |                61 |
+--------+--------------------------------------+-------------------+
|   2005 | Slough                               |                31 |
+--------+--------------------------------------+-------------------+
|   2005 | Stoke-on-Trent                       |                67 |
+--------+--------------------------------------+-------------------+
|   2005 | Blaenau Gwent                        |                 6 |
+--------+--------------------------------------+-------------------+
|   2005 | Bradford                             |               112 |
+--------+--------------------------------------+-------------------+
|   2005 | Dudley                               |                67 |
+--------+--------------------------------------+-------------------+
|   2005 | North Somerset                       |                41 |
+--------+--------------------------------------+-------------------+
|   2005 | Conwy                                |                21 |
+--------+--------------------------------------+-------------------+
|   2005 | Newport                              |                24 |
+--------+--------------------------------------+-------------------+
|   2005 | Redcar and Cleveland                 |                22 |
+--------+--------------------------------------+-------------------+
|   2005 | Camden                               |                57 |
+--------+--------------------------------------+-------------------+
|   2005 | York                                 |                30 |
+--------+--------------------------------------+-------------------+
|   2005 | Dorset                               |                95 |
+--------+--------------------------------------+-------------------+
|   2005 | Ceredigion                           |                19 |
+--------+--------------------------------------+-------------------+
|   2005 | Clackmannanshire                     |                 6 |
+--------+--------------------------------------+-------------------+
|   2005 | Bridgend                             |                25 |
+--------+--------------------------------------+-------------------+
|   2005 | Aberdeenshire                        |                40 |
+--------+--------------------------------------+-------------------+
|   2005 | Darlington                           |                26 |
+--------+--------------------------------------+-------------------+
|   2005 | Somerset                             |               111 |
+--------+--------------------------------------+-------------------+
|   2005 | Cheshire East                        |               119 |
+--------+--------------------------------------+-------------------+
|   2005 | Highland                             |                47 |
+--------+--------------------------------------+-------------------+
|   2005 | Powys                                |                26 |
+--------+--------------------------------------+-------------------+
|   2005 | South Tyneside                       |                25 |
+--------+--------------------------------------+-------------------+
|   2005 | Nottingham                           |                82 |
+--------+--------------------------------------+-------------------+
|   2005 | Gwynedd                              |                21 |
+--------+--------------------------------------+-------------------+
|   2005 | Sheffield                            |               144 |
+--------+--------------------------------------+-------------------+
|   2005 | Aberdeen City                        |                23 |
+--------+--------------------------------------+-------------------+
|   2005 | Stockport                            |                52 |
+--------+--------------------------------------+-------------------+
|   2005 | Bracknell Forest                     |                19 |
+--------+--------------------------------------+-------------------+
|   2005 | Luton                                |                20 |
+--------+--------------------------------------+-------------------+
|   2005 | Bexley                               |                41 |
+--------+--------------------------------------+-------------------+
|   2005 | Bristol, City of                     |                95 |
+--------+--------------------------------------+-------------------+
|   2005 | Knowsley                             |                36 |
+--------+--------------------------------------+-------------------+
|   2005 | East Dunbartonshire                  |                11 |
+--------+--------------------------------------+-------------------+
|   2005 | South Gloucestershire                |                59 |
+--------+--------------------------------------+-------------------+
|   2005 | Blackpool                            |                23 |
+--------+--------------------------------------+-------------------+
|   2005 | Birmingham                           |               275 |
+--------+--------------------------------------+-------------------+
|   2005 | Perth and Kinross                    |                21 |
+--------+--------------------------------------+-------------------+
|   2005 | Poole                                |                30 |
+--------+--------------------------------------+-------------------+
|   2005 | Tower Hamlets                        |                66 |
+--------+--------------------------------------+-------------------+
|   2005 | Moray                                |                13 |
+--------+--------------------------------------+-------------------+
|   2005 | Peterborough                         |                71 |
+--------+--------------------------------------+-------------------+
|   2005 | Dumfries & Galloway                  |                42 |
+--------+--------------------------------------+-------------------+
|   2005 | Herefordshire, County of             |                54 |
+--------+--------------------------------------+-------------------+
|   2005 | Bournemouth                          |                38 |
+--------+--------------------------------------+-------------------+
|   2005 | Portsmouth                           |                49 |
+--------+--------------------------------------+-------------------+
|   2005 | Blackburn with Darwen                |                35 |
+--------+--------------------------------------+-------------------+
|   2005 | Halton                               |                25 |
+--------+--------------------------------------+-------------------+
|   2005 | Wokingham                            |                32 |
+--------+--------------------------------------+-------------------+
|   2005 | Northumberland                       |                83 |
+--------+--------------------------------------+-------------------+
|   2005 | Devon                                |               194 |
+--------+--------------------------------------+-------------------+
|   2005 | Falkirk                              |                18 |
+--------+--------------------------------------+-------------------+
|   2005 | Leeds                                |               182 |
+--------+--------------------------------------+-------------------+
|   2005 | Swindon                              |                33 |
+--------+--------------------------------------+-------------------+
|   2005 | Swansea                              |                53 |
+--------+--------------------------------------+-------------------+
|   2005 | Redbridge                            |                63 |
+--------+--------------------------------------+-------------------+
|   2005 | Southend-on-Sea                      |                34 |
+--------+--------------------------------------+-------------------+
|   2005 | East Renfrewshire                    |                 9 |
+--------+--------------------------------------+-------------------+
|   2005 | Worcestershire                       |               108 |
+--------+--------------------------------------+-------------------+
|   2005 | Lincolnshire                         |               177 |
+--------+--------------------------------------+-------------------+
|   2005 | Leicestershire                       |               126 |
+--------+--------------------------------------+-------------------+
|   2005 | Waltham Forest                       |                58 |
+--------+--------------------------------------+-------------------+
|   2005 | Bolton                               |                54 |
+--------+--------------------------------------+-------------------+
|   2005 | Denbighshire                         |                24 |
+--------+--------------------------------------+-------------------+
|   2005 | West Berkshire                       |                26 |
+--------+--------------------------------------+-------------------+
|   2005 | North Yorkshire                      |               132 |
+--------+--------------------------------------+-------------------+
|   2005 | Rutland                              |                 7 |
+--------+--------------------------------------+-------------------+
|   2005 | East Sussex                          |               128 |
+--------+--------------------------------------+-------------------+
|   2005 | Wakefield                            |                65 |
+--------+--------------------------------------+-------------------+
|   2005 | Hertfordshire                        |               288 |
+--------+--------------------------------------+-------------------+
|   2005 | Bromley                              |                49 |
+--------+--------------------------------------+-------------------+
|   2005 | Cambridgeshire                       |               151 |
+--------+--------------------------------------+-------------------+
|   2005 | Stirling                             |                17 |
+--------+--------------------------------------+-------------------+
|   2005 | Bath and North East Somerset         |                38 |
+--------+--------------------------------------+-------------------+
|   2005 | Merthyr Tydfil                       |                16 |
+--------+--------------------------------------+-------------------+
|   2005 | Nottinghamshire                      |               187 |
+--------+--------------------------------------+-------------------+
|   2005 | North Tyneside                       |                44 |
+--------+--------------------------------------+-------------------+
|   2005 | Rhondda, Cynon, Taff                 |                41 |
+--------+--------------------------------------+-------------------+
|   2005 | Midlothian                           |                13 |
+--------+--------------------------------------+-------------------+
|   2005 | Kingston upon Thames                 |                37 |
+--------+--------------------------------------+-------------------+
|   2005 | Caerphilly                           |                20 |
+--------+--------------------------------------+-------------------+
|   2005 | Newham                               |                55 |
+--------+--------------------------------------+-------------------+
|   2005 | Lambeth                              |                71 |
+--------+--------------------------------------+-------------------+
|   2005 | Hampshire                            |               242 |
+--------+--------------------------------------+-------------------+
|   2005 | City of London                       |                32 |
+--------+--------------------------------------+-------------------+
|   2005 | Southwark                            |                80 |
+--------+--------------------------------------+-------------------+
|   2005 | Hackney                              |                62 |
+--------+--------------------------------------+-------------------+
|   2005 | Northamptonshire                     |               147 |
+--------+--------------------------------------+-------------------+
|   2005 | Wandsworth                           |                61 |
+--------+--------------------------------------+-------------------+
|   2005 | Edinburgh, City of                   |               113 |
+--------+--------------------------------------+-------------------+
|   2005 | Angus                                |                15 |
+--------+--------------------------------------+-------------------+
|   2005 | Sunderland                           |                65 |
+--------+--------------------------------------+-------------------+
|   2005 | Haringey                             |                40 |
+--------+--------------------------------------+-------------------+
|   2005 | Stockton-on-Tees                     |                32 |
+--------+--------------------------------------+-------------------+
|   2005 | Norfolk                              |               199 |
+--------+--------------------------------------+-------------------+
|   2005 | Bury                                 |                49 |
+--------+--------------------------------------+-------------------+
|   2005 | Derby                                |                49 |
+--------+--------------------------------------+-------------------+
|   2005 | Essex                                |               300 |
+--------+--------------------------------------+-------------------+
|   2005 | Buckinghamshire                      |               126 |
+--------+--------------------------------------+-------------------+
|   2005 | Gateshead                            |                43 |
+--------+--------------------------------------+-------------------+
|   2005 | Cheshire West and Chester            |                87 |
+--------+--------------------------------------+-------------------+
|   2005 | Manchester                           |               136 |
+--------+--------------------------------------+-------------------+
|   2005 | Coventry                             |                66 |
+--------+--------------------------------------+-------------------+
|   2005 | Reading                              |                34 |
+--------+--------------------------------------+-------------------+
|   2005 | The Vale of Glamorgan                |                34 |
+--------+--------------------------------------+-------------------+
|   2005 | Barnsley                             |                65 |
+--------+--------------------------------------+-------------------+
|   2005 | Plymouth                             |                69 |
+--------+--------------------------------------+-------------------+
|   2005 | Harrow                               |                35 |
+--------+--------------------------------------+-------------------+
|   2005 | London Airport (Heathrow)            |                 3 |
+--------+--------------------------------------+-------------------+
|   2005 | Havering                             |                43 |
+--------+--------------------------------------+-------------------+
|   2005 | Leicester                            |                66 |
+--------+--------------------------------------+-------------------+
|   2005 | Windsor and Maidenhead               |                27 |
+--------+--------------------------------------+-------------------+
|   2005 | Rochdale                             |                50 |
+--------+--------------------------------------+-------------------+

## Join 2 aggregation 3

In [7]:
import pyodbc
from tabulate import tabulate

# Connection string to connect to the SQL Server database
connection_string = "Driver={ODBC Driver 17 for SQL Server};Server=MY_GENIE\\SQLEXPRESS;Database=ACCIDENTS;Trusted_Connection=yes;"
cnxn = pyodbc.connect(connection_string)
cursor = cnxn.cursor()

# Title for the output
title = "This query calculates the total number of casualties for each type of pedestrian human control, grouping the results by the meaning of each control type"

# SQL query to execute
my_query = """
select  hc.Meaning as Pedestrian_Human_Control, COUNT(a.Number_Of_Casualities) as Number_Of_Casualities
from Accidents a
join Pedestrian_Human_Control hc
on a.Pedestrian_Crossing_Human_Control = hc.Pedestrian_Crossing_Human_Control
group by hc.Meaning
"""

# Print the title and the SQL query
print(title)
print("\nSQL Query:")
print(my_query)

# Execute the query
cursor.execute(my_query)

# Fetch all the results
rows = cursor.fetchall()

# Define the headers, if your result includes headers you can fetch them via cursor.description
headers = [column[0] for column in cursor.description]

# Printing the results in a table format
print("\nResults:")
print(tabulate(rows, headers=headers, tablefmt='grid'))

# Clean up: close the cursor and the connection
cursor.close()
cnxn.close()

This query calculates the total number of casualties for each type of pedestrian human control, grouping the results by the meaning of each control type

SQL Query:

select  hc.Meaning as Pedestrian_Human_Control, COUNT(a.Number_Of_Casualities) as Number_Of_Casualities
from Accidents a
join Pedestrian_Human_Control hc
on a.Pedestrian_Crossing_Human_Control = hc.Pedestrian_Crossing_Human_Control
group by hc.Meaning


Results:
+------------------------------------+-------------------------+
| Pedestrian_Human_Control           |   Number_Of_Casualities |
+====================================+=========================+
| Control by other authorised person |                     736 |
+------------------------------------+-------------------------+
| Control by school crossing patrol  |                     441 |
+------------------------------------+-------------------------+
| None within 50 metres              |                  202923 |
+------------------------------------+-------------------------+

## Query on View 2

In [8]:
import pyodbc
from tabulate import tabulate

# Connection string to connect to the SQL Server database
connection_string = "Driver={ODBC Driver 17 for SQL Server};Server=MY_GENIE\\SQLEXPRESS;Database=ACCIDENTS;Trusted_Connection=yes;"
cnxn = pyodbc.connect(connection_string)
cursor = cnxn.cursor()

# Title for the output
title = "This query calculates the total number of accidents for each combination of local district authority and police response type, grouping the results by these categories."

# SQL query to execute
my_query = """
select Local_District_Authority,count(*) as No_of_accidents,Meaning as Did_Police_Arrive
from temp2
group by Meaning,Local_District_Authority
"""

# Print the title and the SQL query
print(title)
print("\nSQL Query:")
print(my_query)

# Execute the query
cursor.execute(my_query)

# Fetch all the results
rows = cursor.fetchall()

# Define the headers, if your result includes headers you can fetch them via cursor.description
headers = [column[0] for column in cursor.description]

# Printing the results in a table format
print("\nResults:")
print(tabulate(rows, headers=headers, tablefmt='grid'))

# Clean up: close the cursor and the connection
cursor.close()
cnxn.close()

This query calculates the total number of accidents for each combination of local district authority and police response type, grouping the results by these categories.

SQL Query:

select Local_District_Authority,count(*) as No_of_accidents,Meaning as Did_Police_Arrive
from temp2
group by Meaning,Local_District_Authority


Results:
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Local_District_Authority     |   No_of_accidents | Did_Police_Arrive                                                        |
+==============================+===================+==========================================================================+
| Aberdeen City                |                76 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Aberdeen City                |               361 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Aberdeenshire                |                57 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Aberdeenshire                |               651 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Adur                         |                56 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Adur                         |               138 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Allerdale                    |                53 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Allerdale                    |               276 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Alnwick                      |                 7 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Alnwick                      |                37 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Amber Valley                 |                89 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Amber Valley                 |               287 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Angus                        |                 5 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Angus                        |               259 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Argyll and Bute              |                31 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Argyll and Bute              |               296 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Arun                         |                85 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Arun                         |               339 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Ashfield                     |                96 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Ashfield                     |                 4 | No - accident was reported using a self completion  form (self rep only) |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Ashfield                     |               315 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Ashford                      |                97 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Ashford                      |                 2 | No - accident was reported using a self completion  form (self rep only) |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Ashford                      |               396 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Aylesbury Vale               |                78 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Aylesbury Vale               |               480 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Babergh                      |                43 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Babergh                      |               294 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barking and Dagenham         |               114 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barking and Dagenham         |                 4 | No - accident was reported using a self completion  form (self rep only) |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barking and Dagenham         |               517 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barnet                       |               220 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barnet                       |                18 | No - accident was reported using a self completion  form (self rep only) |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barnet                       |              1217 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barnsley                     |               139 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barnsley                     |                 4 | No - accident was reported using a self completion  form (self rep only) |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barnsley                     |               661 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barrow-in-Furness            |                44 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Barrow-in-Furness            |               146 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Basildon                     |               126 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Basildon                     |               429 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Basingstoke and Deane        |                83 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Basingstoke and Deane        |               412 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bassetlaw                    |                74 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bassetlaw                    |                 2 | No - accident was reported using a self completion  form (self rep only) |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bassetlaw                    |               373 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bath and North East Somerset |               102 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bath and North East Somerset |               346 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bedford                      |               107 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bedford                      |               431 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Berwick-upon-Tweed           |                28 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bexley                       |                74 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bexley                       |                 6 | No - accident was reported using a self completion  form (self rep only) |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bexley                       |               535 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Birmingham                   |              1022 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Birmingham                   |              2863 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blaby                        |                55 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blaby                        |               325 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blackburn with Darwen        |                 4 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blackburn with Darwen        |               546 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blackpool                    |               562 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blaenau Gwent                |                19 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blaenau Gwent                |               126 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blyth Valley                 |                21 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Blyth Valley                 |                63 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bolsover                     |                53 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bolsover                     |               254 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bolton                       |               146 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bolton                       |               604 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Boston                       |                52 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Boston                       |               239 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bournemouth                  |               175 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bournemouth                  |                 4 | No - accident was reported using a self completion  form (self rep only) |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bournemouth                  |               507 | Yes                                                                      |
+------------------------------+-------------------+--------------------------------------------------------------------------+
| Bracknell Forest             |                44 | No                                                                       |
+------------------------------+-------------------+--------------------------------------------------------------------------+

## Join 3

In [9]:
import pyodbc
from tabulate import tabulate

# Connection string to connect to the SQL Server database
connection_string = "Driver={ODBC Driver 17 for SQL Server};Server=MY_GENIE\\SQLEXPRESS;Database=ACCIDENTS;Trusted_Connection=yes;"
cnxn = pyodbc.connect(connection_string)
cursor = cnxn.cursor()

# Title for the output
title = "This query calculates the total number of unique accidents for each IMD decile category, sorting the results in descending order by the number of accidents."

# SQL query to execute
my_query = """
select i.Meaning as IMD_decile_category ,count(distinct v.Accident_Index) as No_of_accidents
from [dbo].[Vehicle] v
join [dbo].[IMD_Decile] i
on i.Driver_IMD_Decile=v.Driver_IMD_Decile
join [dbo].[Accidents] a
on v.Accident_Index=a.Accident_Index
group by i.Meaning
order by No_of_accidents desc
"""

# Print the title and the SQL query
print(title)
print("\nSQL Query:")
print(my_query)

# Execute the query
cursor.execute(my_query)

# Fetch all the results
rows = cursor.fetchall()

# Define the headers, if your result includes headers you can fetch them via cursor.description
headers = [column[0] for column in cursor.description]

# Printing the results in a table format
print("\nResults:")
print(tabulate(rows, headers=headers, tablefmt='grid'))

# Clean up: close the cursor and the connection
cursor.close()
cnxn.close()

This query calculates the total number of unique accidents for each IMD decile category, sorting the results in descending order by the number of accidents.

SQL Query:

select i.Meaning as IMD_decile_category ,count(distinct v.Accident_Index) as No_of_accidents
from [dbo].[Vehicle] v
join [dbo].[IMD_Decile] i
on i.Driver_IMD_Decile=v.Driver_IMD_Decile
join [dbo].[Accidents] a
on v.Accident_Index=a.Accident_Index
group by i.Meaning
order by No_of_accidents desc


Results:
+-----------------------+-------------------+
| IMD_decile_category   |   No_of_accidents |
+=======================+===================+
| More deprived 30-40%  |             20378 |
+-----------------------+-------------------+
| More deprived 10-20%  |             20267 |
+-----------------------+-------------------+
| More deprived 40-50%  |             20194 |
+-----------------------+-------------------+
| More deprived 20-30%  |             19996 |
+-----------------------+-------------------+
| Less deprived 40-50%  |             19796 |
+-----------------------+-------------------+
| Less deprived 30-40%  |             19159 |
+-----------------------+-------------------+
| Less deprived 20-30%  |             18669 |
+-----------------------+-------------------+
| Most deprived 10%     |             18483 |
+-----------------------+-------------------+
| Less deprived 10-20%  |             18275 |
+-----------------------+-------------------+
| Least deprived 10%    |             16255 |
+-----------------------+-------------------+